/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 desktop_computer.glb 
Author: thalyspz (https://sketchfab.com/thalyspz)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/desktop-computer-e9e6f5a23dea4ee783f50eec9b327f8c
Title: desktop computer
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Desktop(props) {
  const { nodes, materials } = useGLTF('/models/desktop_computer.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.661, 0.883, -2.254]} rotation={[-Math.PI, 0, 0]} scale={[-0.198, 0.187, 0.198]}>
        <mesh geometry={nodes.Object_54.geometry} material={materials.preto} />
        <mesh geometry={nodes.Object_55.geometry} material={materials.Materiais} />
        <mesh geometry={nodes.Object_56.geometry} material={materials['Materiais.001']} />
      </group>
      <mesh geometry={nodes.Object_4.geometry} material={materials.preto} position={[0, 0.541, 0.545]} rotation={[0, 0, -Math.PI]} scale={[-1.43, 0.126, 4.939]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.preto} position={[-5.094, 0.541, 4.034]} rotation={[Math.PI, -Math.PI / 2, 0]} scale={[-1.43, 0.126, 3.678]} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.preto} position={[-0.03, -1.232, -4.184]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[-1.755, 0.13, 1.23]} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.preto} position={[-8.469, -1.232, 4.103]} rotation={[0, 0.087, Math.PI / 2]} scale={[-1.755, 0.13, 1.23]} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.preto} position={[1.297, -1.232, 2.669]} rotation={[Math.PI, 0, -Math.PI / 2]} scale={[-1.755, 0.13, 2.615]} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.preto} position={[-0.645, -1.232, 5.337]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[-1.755, 0.13, 1.82]} />
      <mesh geometry={nodes.Object_16.geometry} material={materials['Materiais.003']} position={[0.216, -0.5, 2.169]} rotation={[0, 0, -Math.PI]} scale={[-1, 0.064, 2.161]} />
      <mesh geometry={nodes.Object_18.geometry} material={materials.preto} position={[0.72, -1.493, 4.02]} rotation={[0, 0, -Math.PI]} scale={[-0.498, 0.064, 1.224]} />
      <mesh geometry={nodes.Object_20.geometry} material={materials['Materiais.005']} position={[-0.526, -0.5, 4.801]} rotation={[0, 0, -Math.PI]} scale={[-1.678, 0.064, 0.503]} />
      <mesh geometry={nodes.Object_22.geometry} material={materials['Materiais.005']} position={[0.72, -1.603, 1.569]} rotation={[0, 0, -Math.PI]} scale={[-0.498, 0.064, 1.224]} />
      <mesh geometry={nodes.Object_24.geometry} material={materials.preto} position={[-7.441, 1.877, 4.201]} scale={[0.508, 1.205, 1.157]} />
      <mesh geometry={nodes.Object_26.geometry} material={materials['Materiais.009']} position={[-7.455, 1.867, 3.084]} rotation={[0, Math.PI / 2, 0]} scale={[0.046, 1.226, 0.508]} />
      <mesh geometry={nodes.Object_28.geometry} material={materials.material_0} position={[-7.451, 1.838, 2.958]} rotation={[Math.PI / 2, 0, 0]} scale={[-0.02, 0.112, 1.167]} />
      <mesh geometry={nodes.Object_30.geometry} material={materials.material_0} position={[-7.524, 3.001, 2.996]} rotation={[-Math.PI / 2, -Math.PI / 6, Math.PI]} scale={[-0.01, 0.067, 0.111]} />
      <mesh geometry={nodes.Object_32.geometry} material={materials.material_0} position={[-7.37, 3.001, 2.996]} rotation={[-Math.PI / 2, 0.575, -Math.PI]} scale={[-0.01, 0.067, 0.111]} />
      <mesh geometry={nodes.Object_34.geometry} material={materials.material_0} position={[-7.239, 1.056, 2.944]} rotation={[-Math.PI / 2, 0.524, -Math.PI]} scale={[-0.023, 0.067, 0.41]} />
      <mesh geometry={nodes.Object_36.geometry} material={materials.material_0} position={[-7.432, 2.519, 2.944]} rotation={[-Math.PI / 2, -Math.PI / 6, Math.PI]} scale={[-0.023, 0.067, 0.41]} />
      <mesh geometry={nodes.Object_38.geometry} material={materials.material_0} position={[-7.702, 1.056, 2.944]} rotation={[-Math.PI / 2, -Math.PI / 6, Math.PI]} scale={[-0.025, 0.067, 0.42]} />
      <mesh geometry={nodes.Object_40.geometry} material={materials.material_0} position={[-7.695, 1.749, 2.944]} rotation={[-Math.PI / 2, 0.611, -Math.PI]} scale={[-0.023, 0.067, 0.41]} />
      <mesh geometry={nodes.Object_42.geometry} material={materials.material_0} position={[-7.233, 1.728, 2.944]} rotation={[-Math.PI / 2, -Math.PI / 6, Math.PI]} scale={[-0.023, 0.067, 0.41]} />
      <mesh geometry={nodes.Object_44.geometry} material={materials.material_0} position={[-7.446, 2.511, 2.944]} rotation={[Math.PI / 2, -0.436, 0]} scale={[-0.023, 0.067, 0.41]} />
      <mesh geometry={nodes.Object_46.geometry} material={materials.preto} position={[0.002, 1.877, -3.33]} rotation={[0, Math.PI / 2, 0]} scale={[0.508, 1.205, 1.157]} />
      <mesh geometry={nodes.Object_48.geometry} material={materials.material_0} position={[-7.418, 1.917, 5.14]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.214, 0.255, 0.242]} />
      <mesh geometry={nodes.Object_50.geometry} material={materials.material_0} position={[-7.418, 1.237, 5.14]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.214, 0.255, 0.242]} />
      <mesh geometry={nodes.Object_52.geometry} material={materials.material_0} position={[-7.418, 2.601, 5.14]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.214, 0.255, 0.242]} />
      <mesh geometry={nodes.Object_58.geometry} material={materials.material_0} position={[0.749, 2.104, -3.276]} rotation={[0, 0, -Math.PI]} scale={[-0.074, 0.016, 0.017]} />
      <mesh geometry={nodes.Object_60.geometry} material={materials.material_0} position={[-0.43, 1.82, -3.091]} rotation={[0, 0, -Math.PI]} scale={[-0.074, 0.016, 0.017]} />
      <mesh geometry={nodes.Object_62.geometry} material={materials.preto} position={[-0.662, 0.692, -0.084]} rotation={[0, 0, -Math.PI]} scale={[-0.295, 0.026, 0.647]} />
      <mesh geometry={nodes.Object_64.geometry} material={materials.material_0} position={[-0.383, 0.629, 0.334]} rotation={[0, 0, -Math.PI]} scale={[-0.025, 0.008, 0.026]} />
      <mesh geometry={nodes.Object_66.geometry} material={materials.material_0} position={[-0.42, 0.721, -0.676]} rotation={[0, 0, -Math.PI]} scale={[-0.033, 0.008, 0.03]} />
      <mesh geometry={nodes.Object_68.geometry} material={materials.material_0} position={[-0.383, 0.639, 0.394]} rotation={[0, 0, -Math.PI]} scale={[-0.025, 0.008, 0.026]} />
      <mesh geometry={nodes.Object_70.geometry} material={materials['Materiais.001']} position={[-0.995, -0.009, 4.977]} rotation={[-2.933, 0.019, 3.09]} scale={[-0.253, 0.423, 0.071]} />
      <mesh geometry={nodes.Object_72.geometry} material={materials.material_0} position={[-0.976, 0.22, 4.923]} rotation={[-1.363, -0.051, 3.123]} scale={[-0.12, 0.005, 0.129]} />
      <mesh geometry={nodes.Object_74.geometry} material={materials['Materiais.007']} position={[0.005, -0.009, 4.977]} rotation={[-3.135, -0.103, -3.076]} scale={[-0.253, 0.423, 0.071]} />
      <mesh geometry={nodes.Object_76.geometry} material={materials['Materiais.007']} position={[1.055, -0.009, 0.487]} rotation={[-0.14, -1.522, -0.075]} scale={[-0.253, 0.423, 0.071]} />
      <mesh geometry={nodes.Object_78.geometry} material={materials.Materiais} position={[0.055, -0.379, 1.487]} rotation={[1.523, -0.014, 1.635]} scale={[-0.253, 0.423, 0.071]} />
      <mesh geometry={nodes.Object_80.geometry} material={materials.Materiais} position={[1.055, -0.009, 4.487]} rotation={[-0.14, -1.522, -0.075]} scale={[-0.253, 0.423, 0.071]} />
      <mesh geometry={nodes.Object_82.geometry} material={materials['Materiais.002']} position={[1.055, -0.009, 3.487]} rotation={[-3.126, 1.105, -3.09]} scale={[-0.253, 0.423, 0.071]} />
      <mesh geometry={nodes.Object_84.geometry} material={materials['Materiais.005']} position={[0, 0.69, -1.74]} scale={[0.241, 0.02, 0.241]} />
      <mesh geometry={nodes.Object_86.geometry} material={materials.material_0} position={[-0.877, 0.721, -0.423]} rotation={[0, 0, -Math.PI]} scale={[-0.038, 0.01, 0.046]} />
      <mesh geometry={nodes.Object_88.geometry} material={materials.material_0} position={[-0.548, 0.719, -0.673]} rotation={[0, 0, -Math.PI]} scale={[-0.033, 0.008, 0.03]} />
      <mesh geometry={nodes.Object_90.geometry} material={materials.material_0} position={[-0.548, 0.719, -0.546]} rotation={[0, 0, -Math.PI]} scale={[-0.033, 0.008, 0.03]} />
      <mesh geometry={nodes.Object_92.geometry} material={materials.material_0} position={[-0.547, 0.719, -0.411]} rotation={[0, 0, -Math.PI]} scale={[-0.033, 0.008, 0.03]} />
      <mesh geometry={nodes.Object_94.geometry} material={materials.material_0} position={[-0.547, 0.719, -0.277]} rotation={[0, 0, -Math.PI]} scale={[-0.033, 0.008, 0.03]} />
      <mesh geometry={nodes.Object_96.geometry} material={materials.material_0} position={[-0.547, 0.719, -0.151]} rotation={[0, 0, -Math.PI]} scale={[-0.033, 0.008, 0.03]} />
      <mesh geometry={nodes.Object_98.geometry} material={materials.material_0} position={[-0.547, 0.719, -0.025]} rotation={[0, 0, -Math.PI]} scale={[-0.033, 0.008, 0.03]} />
      <mesh geometry={nodes.Object_100.geometry} material={materials.material_0} position={[-0.449, 0.719, 0.089]} rotation={[0, 0, -Math.PI]} scale={[-0.033, 0.008, 0.03]} />
      <mesh geometry={nodes.Object_102.geometry} material={materials.material_0} position={[-0.449, 0.719, 0.157]} rotation={[0, 0, -Math.PI]} scale={[-0.033, 0.008, 0.03]} />
      <mesh geometry={nodes.Object_104.geometry} material={materials.material_0} position={[-0.449, 0.719, 0.228]} rotation={[0, 0, -Math.PI]} scale={[-0.033, 0.008, 0.03]} />
      <mesh geometry={nodes.Object_106.geometry} material={materials.material_0} position={[-0.521, 0.719, 0.089]} rotation={[0, 0, -Math.PI]} scale={[-0.033, 0.008, 0.03]} />
      <mesh geometry={nodes.Object_108.geometry} material={materials.material_0} position={[-0.521, 0.719, 0.158]} rotation={[0, 0, -Math.PI]} scale={[-0.033, 0.008, 0.03]} />
      <mesh geometry={nodes.Object_110.geometry} material={materials.material_0} position={[-0.521, 0.719, 0.228]} rotation={[0, 0, -Math.PI]} scale={[-0.033, 0.008, 0.03]} />
      <mesh geometry={nodes.Object_112.geometry} material={materials.material_0} position={[-0.653, 0.719, -0.673]} rotation={[0, 0, -Math.PI]} scale={[-0.033, 0.008, 0.03]} />
      <mesh geometry={nodes.Object_114.geometry} material={materials.material_0} position={[-0.774, 0.719, -0.673]} rotation={[0, 0, -Math.PI]} scale={[-0.033, 0.008, 0.03]} />
      <mesh geometry={nodes.Object_116.geometry} material={materials.material_0} position={[-0.874, 0.719, -0.673]} rotation={[0, 0, -Math.PI]} scale={[-0.033, 0.008, 0.03]} />
      <mesh geometry={nodes.Object_118.geometry} material={materials.material_0} position={[-0.655, 0.719, -0.546]} rotation={[0, 0, -Math.PI]} scale={[-0.033, 0.008, 0.03]} />
      <mesh geometry={nodes.Object_120.geometry} material={materials.material_0} position={[-0.769, 0.719, -0.546]} rotation={[0, 0, -Math.PI]} scale={[-0.033, 0.008, 0.03]} />
      <mesh geometry={nodes.Object_122.geometry} material={materials.material_0} position={[-0.877, 0.719, -0.546]} rotation={[0, 0, -Math.PI]} scale={[-0.033, 0.008, 0.03]} />
      <mesh geometry={nodes.Object_124.geometry} material={materials.material_0} position={[-0.661, 0.719, -0.411]} rotation={[0, 0, -Math.PI]} scale={[-0.033, 0.008, 0.03]} />
      <mesh geometry={nodes.Object_126.geometry} material={materials.material_0} position={[-0.758, 0.719, -0.411]} rotation={[0, 0, -Math.PI]} scale={[-0.033, 0.008, 0.03]} />
      <mesh geometry={nodes.Object_128.geometry} material={materials.material_0} position={[-0.653, 0.719, -0.277]} rotation={[0, 0, -Math.PI]} scale={[-0.033, 0.008, 0.03]} />
      <mesh geometry={nodes.Object_130.geometry} material={materials.material_0} position={[-0.76, 0.719, -0.277]} rotation={[0, 0, -Math.PI]} scale={[-0.033, 0.008, 0.03]} />
      <mesh geometry={nodes.Object_132.geometry} material={materials.material_0} position={[-0.66, 0.719, -0.151]} rotation={[0, 0, -Math.PI]} scale={[-0.033, 0.008, 0.03]} />
      <mesh geometry={nodes.Object_134.geometry} material={materials.material_0} position={[-0.761, 0.719, -0.151]} rotation={[0, 0, -Math.PI]} scale={[-0.033, 0.008, 0.03]} />
      <mesh geometry={nodes.Object_136.geometry} material={materials.material_0} position={[-0.656, 0.719, -0.025]} rotation={[0, 0, -Math.PI]} scale={[-0.033, 0.008, 0.03]} />
      <mesh geometry={nodes.Object_138.geometry} material={materials.material_0} position={[-0.765, 0.719, -0.025]} rotation={[0, 0, -Math.PI]} scale={[-0.033, 0.008, 0.03]} />
      <mesh geometry={nodes.Object_140.geometry} material={materials.material_0} position={[-0.89, 0.719, 0.136]} rotation={[0, 0, -Math.PI]} scale={[-0.033, 0.008, 0.03]} />
      <mesh geometry={nodes.Object_142.geometry} material={materials.material_0} position={[-0.889, 0.719, 0.213]} rotation={[0, 0, -Math.PI]} scale={[-0.033, 0.008, 0.03]} />
      <mesh geometry={nodes.Object_144.geometry} material={materials.material_0} position={[-0.888, 0.719, 0.287]} rotation={[0, 0, -Math.PI]} scale={[-0.033, 0.008, 0.03]} />
      <mesh geometry={nodes.Object_146.geometry} material={materials.material_0} position={[-0.799, 0.714, 0.21]} rotation={[0, 0, -Math.PI]} scale={[-0.033, 0.008, 0.03]} />
      <mesh geometry={nodes.Object_148.geometry} material={materials.material_0} position={[-0.604, 0.719, 0.092]} rotation={[0, 0, -Math.PI]} scale={[-0.033, 0.008, 0.067]} />
      <mesh geometry={nodes.Object_150.geometry} material={materials.material_0} position={[-0.696, 0.719, 0.051]} rotation={[0, 0, -Math.PI]} scale={[-0.033, 0.008, 0.026]} />
      <mesh geometry={nodes.Object_152.geometry} material={materials.material_0} position={[-0.478, 0.719, 0.313]} rotation={[0, 0, -Math.PI]} scale={[-0.033, 0.008, 0.03]} />
      <mesh geometry={nodes.Object_154.geometry} material={materials.material_0} position={[-0.478, 0.719, 0.401]} rotation={[0, 0, -Math.PI]} scale={[-0.033, 0.008, 0.03]} />
      <mesh geometry={nodes.Object_156.geometry} material={materials.material_0} position={[-0.478, 0.719, 0.489]} rotation={[0, 0, -Math.PI]} scale={[-0.033, 0.008, 0.03]} />
      <mesh geometry={nodes.Object_158.geometry} material={materials.material_0} position={[-0.587, 0.719, 0.489]} rotation={[0, 0, -Math.PI]} scale={[-0.033, 0.008, 0.03]} />
      <mesh geometry={nodes.Object_160.geometry} material={materials.material_0} position={[-0.586, 0.719, 0.401]} rotation={[0, 0, -Math.PI]} scale={[-0.033, 0.008, 0.03]} />
      <mesh geometry={nodes.Object_162.geometry} material={materials.material_0} position={[-0.581, 0.719, 0.313]} rotation={[0, 0, -Math.PI]} scale={[-0.033, 0.008, 0.03]} />
      <mesh geometry={nodes.Object_164.geometry} material={materials.material_0} position={[-0.704, 0.719, 0.313]} rotation={[0, 0, -Math.PI]} scale={[-0.033, 0.008, 0.03]} />
      <mesh geometry={nodes.Object_166.geometry} material={materials.material_0} position={[-0.704, 0.719, 0.401]} rotation={[0, 0, -Math.PI]} scale={[-0.033, 0.008, 0.03]} />
      <mesh geometry={nodes.Object_168.geometry} material={materials.material_0} position={[-0.705, 0.719, 0.489]} rotation={[0, 0, -Math.PI]} scale={[-0.033, 0.008, 0.03]} />
      <mesh geometry={nodes.Object_170.geometry} material={materials.material_0} position={[-0.799, 0.718, 0.331]} rotation={[0, 0, -Math.PI]} scale={[-0.033, 0.008, 0.06]} />
      <mesh geometry={nodes.Object_172.geometry} material={materials.material_0} position={[-0.799, 0.719, 0.451]} rotation={[0, 0, -Math.PI]} scale={[-0.033, 0.008, 0.03]} />
      <mesh geometry={nodes.Object_174.geometry} material={materials.material_0} position={[-0.834, 0.685, 0.526]} rotation={[0, 0, -Math.PI]} scale={[-0.073, 0.008, 0.03]} />
      <mesh geometry={nodes.Object_176.geometry} material={materials.material_0} position={[-0.852, 0.719, 0.522]} rotation={[0, 0, -Math.PI]} scale={[-0.072, 0.008, 0.03]} />
      <mesh geometry={nodes.Object_178.geometry} material={materials['Materiais.008']} position={[-0.66, 0.7, 1.264]} rotation={[0, 0, -Math.PI]} scale={[-0.383, 0.003, 0.298]} />
      <mesh geometry={nodes.Object_180.geometry} material={materials.material_0} position={[-0.545, 0.738, 1.23]} scale={[0.185, 0.042, 0.14]} />
      <mesh geometry={nodes.Object_182.geometry} material={materials.material_0} position={[-0.446, 0.787, 1.223]} rotation={[-Math.PI / 2, 0, 0]} scale={[-0.047, 0.012, 0.047]} />
      <mesh geometry={nodes.Object_184.geometry} material={materials.preto} position={[-0.856, 1.89, 3.278]} rotation={[-0.003, -0.822, -1.459]} scale={[-0.762, 0.082, 1.238]} />
      <mesh geometry={nodes.Object_186.geometry} material={materials.preto} position={[-4.108, 0.697, 3.426]} rotation={[0, 0, -Math.PI]} scale={[-0.531, 0.026, 0.531]} />
      <mesh geometry={nodes.Object_188.geometry} material={materials.material_0} position={[-5.078, 0.685, 3.428]} rotation={[0.013, -1.133, -0.024]} scale={[0.185, 0.042, 0.14]} />
      <mesh geometry={nodes.Object_190.geometry} material={materials.material_0} position={[-5.026, 0.712, 3.498]} rotation={[-2.521, -0.388, -1.375]} scale={[-0.047, 0.012, 0.047]} />
      <mesh geometry={nodes.Object_192.geometry} material={materials.material_0} position={[-3.71, 0.9, 3.794]} rotation={[-0.248, 0.012, 3.073]} scale={[-0.065, 0.013, 0.059]} />
      <mesh geometry={nodes.Object_194.geometry} material={materials.material_0} position={[-4.543, 0.911, 3.011]} rotation={[-0.248, 0.012, 3.073]} scale={[-0.065, 0.013, 0.059]} />
      <mesh geometry={nodes.Object_196.geometry} material={materials.material_0} position={[-3.675, 0.823, 3.42]} rotation={[-0.248, 0.012, 3.073]} scale={[-0.065, 0.013, 0.059]} />
      <mesh geometry={nodes.Object_198.geometry} material={materials.material_0} position={[-3.668, 0.79, 3.234]} rotation={[-0.248, 0.012, 3.073]} scale={[-0.065, 0.013, 0.059]} />
      <mesh geometry={nodes.Object_200.geometry} material={materials.material_0} position={[-3.682, 0.766, 3.036]} rotation={[-0.162, -0.005, 3.11]} scale={[-0.065, 0.013, 0.059]} />
      <mesh geometry={nodes.Object_202.geometry} material={materials.material_0} position={[-3.892, 0.798, 3.228]} rotation={[-0.248, 0.012, 3.073]} scale={[-0.065, 0.013, 0.059]} />
      <mesh geometry={nodes.Object_204.geometry} material={materials.material_0} position={[-4.145, 0.761, 3.031]} rotation={[-0.269, 0.02, 3.133]} scale={[-0.134, 0.013, 0.059]} />
      <mesh geometry={nodes.Object_206.geometry} material={materials.material_0} position={[-3.892, 0.753, 3.045]} rotation={[-0.248, -0.005, -3.141]} scale={[-0.065, 0.013, 0.059]} />
      <mesh geometry={nodes.Object_208.geometry} material={materials.material_0} position={[-3.892, 0.838, 3.429]} rotation={[-0.248, 0.012, 3.073]} scale={[-0.065, 0.013, 0.059]} />
      <mesh geometry={nodes.Object_210.geometry} material={materials.material_0} position={[-3.694, 0.874, 3.614]} rotation={[-0.248, 0.012, 3.073]} scale={[-0.065, 0.013, 0.059]} />
      <mesh geometry={nodes.Object_212.geometry} material={materials.material_0} position={[-3.892, 0.909, 3.778]} rotation={[-0.248, 0.012, 3.073]} scale={[-0.065, 0.013, 0.059]} />
      <mesh geometry={nodes.Object_214.geometry} material={materials.material_0} position={[-4.2, 0.841, 3.377]} rotation={[-2.793, -1.564, 0.614]} scale={[-0.05, 0.013, 0.04]} />
      <mesh geometry={nodes.Object_216.geometry} material={materials.material_0} position={[-4.383, 0.764, 3.045]} rotation={[-0.248, 0.012, 3.073]} scale={[-0.065, 0.013, 0.059]} />
      <mesh geometry={nodes.Object_218.geometry} material={materials.material_0} position={[-4.089, 0.801, 3.236]} rotation={[-0.248, 0.012, 3.073]} scale={[-0.065, 0.013, 0.059]} />
      <mesh geometry={nodes.Object_220.geometry} material={materials.material_0} position={[-4.442, 0.839, 3.198]} rotation={[-0.248, 0.012, 3.073]} scale={[-0.065, 0.013, 0.059]} />
      <mesh geometry={nodes.Object_222.geometry} material={materials.material_0} position={[-3.897, 0.928, 3.587]} rotation={[-0.248, 0.012, 3.073]} scale={[-0.065, 0.013, 0.059]} />
      <mesh geometry={nodes.Object_224.geometry} material={materials.material_0} position={[-4.074, 0.917, 3.781]} rotation={[-0.248, 0.012, 3.073]} scale={[-0.065, 0.013, 0.059]} />
      <mesh geometry={nodes.Object_226.geometry} material={materials['Materiais.008']} position={[0.01, 0.738, -1.738]} scale={[0.115, 0.005, 0.115]} />
      <mesh geometry={nodes.Object_228.geometry} material={materials.material_0} position={[-4.288, 0.928, 3.7]} rotation={[-0.248, 0.012, 3.073]} scale={[-0.065, 0.013, 0.059]} />
      <mesh geometry={nodes.Object_230.geometry} material={materials.material_0} position={[-4.449, 0.928, 3.7]} rotation={[-0.248, 0.012, 3.073]} scale={[-0.065, 0.013, 0.059]} />
      <mesh geometry={nodes.Object_232.geometry} material={materials.material_0} position={[-4.288, 0.928, 3.523]} rotation={[-0.248, 0.012, 3.073]} scale={[-0.065, 0.013, 0.059]} />
      <mesh geometry={nodes.Object_234.geometry} material={materials.material_0} position={[-4.449, 0.928, 3.523]} rotation={[-0.248, 0.012, 3.073]} scale={[-0.065, 0.013, 0.059]} />
      <mesh geometry={nodes.Object_236.geometry} material={materials['Materiais.003']} position={[0.238, 2.035, -0.622]} rotation={[3.14, -0.002, 1.457]} scale={[0.633, 0.068, 1.027]} />
      <mesh geometry={nodes.Object_238.geometry} material={materials['Materiais.008']} position={[0.693, 0.738, -0.234]} rotation={[0, 0, -Math.PI]} scale={[-0.553, 0.041, 0.43]} />
      <mesh geometry={nodes.Object_240.geometry} material={materials['Materiais.008']} position={[-0.342, 2.087, 2.883]} rotation={[3.136, 0.862, 2.958]} scale={[-0.226, 0.031, 0.071]} />
      <mesh geometry={nodes.Object_242.geometry} material={materials['Materiais.008']} position={[-1.279, 2.108, 3.741]} rotation={[3.136, 0.862, 2.958]} scale={[-0.226, 0.031, 0.071]} />
      <mesh geometry={nodes.Object_244.geometry} material={materials['Materiais.008']} position={[-0.381, 0.757, 3.746]} rotation={[0, -Math.PI / 4, -Math.PI]} scale={[-0.383, 0.083, 1.277]} />
      <mesh geometry={nodes.Object_246.geometry} material={materials['Materiais.005']} position={[0.356, 1.947, -3.635]} rotation={[-1.555, -0.008, 0.007]} scale={[0.633, 0.068, 0.882]} />
      <mesh geometry={nodes.Object_248.geometry} material={materials.Materiais} position={[-2.287, 0.714, 3.427]} rotation={[-0.227, 0.857, 1.717]} scale={[-0.048, 0.048, 0.048]} />
      <mesh geometry={nodes.Object_250.geometry} material={materials.material_0} position={[-2.746, 0.703, 3.596]} rotation={[0, 0, -Math.PI]} scale={[-0.383, 0.003, 0.204]} />
      <mesh geometry={nodes.Object_252.geometry} material={materials.material_0} position={[-2.599, 0.669, 3.071]} rotation={[0, 0, -Math.PI]} scale={[-0.328, 0.003, 0.175]} />
      <mesh geometry={nodes.Object_254.geometry} material={materials.material_0} position={[-1.897, 0.67, 3.243]} rotation={[0, 0, -Math.PI]} scale={[-0.328, 0.003, 0.175]} />
      <mesh geometry={nodes.Object_256.geometry} material={materials['Materiais.003']} position={[-2.691, -0.377, -0.223]} scale={[1.094, 0.076, 1.161]} />
      <mesh geometry={nodes.Object_258.geometry} material={materials.preto} position={[-3.478, -2.522, 0.57]} scale={0.145} />
      <mesh geometry={nodes.Object_260.geometry} material={materials.material_0} position={[-3.481, -2.512, -1.048]} scale={0.145} />
      <mesh geometry={nodes.Object_262.geometry} material={materials.material_0} position={[-1.918, -2.522, 0.57]} scale={0.145} />
      <mesh geometry={nodes.Object_264.geometry} material={materials['Materiais.003']} position={[-1.913, -2.482, -1.067]} scale={0.145} />
      <mesh geometry={nodes.Object_266.geometry} material={materials['Materiais.005']} position={[0.206, 2.035, -0.604]} rotation={[3.14, -0.002, 1.457]} scale={[0.569, 0.061, 0.923]} />
      <mesh geometry={nodes.Object_268.geometry} material={materials.material_0} position={[-0.925, 1.915, 3.208]} rotation={[-0.003, -0.822, -1.459]} scale={[-0.677, 0.073, 1.113]} />
    </group>
  )
}

useGLTF.preload('/models/desktop_computer.glb')
